package in.pragati.domain.enums;
public enum AuditAction {
    LOGIN, ALLOCATION_STARTED, ALLOCATION_COMPLETED, ALLOCATION_INFEASIBLE, ALLOCATION_FAILED,
    SIMULATION_COMPLETED, REALLOCATION_COMPLETED, POLICY_UPDATED, SCENARIO_LOADED,
    OPPORTUNITY_CREATED, OPPORTUNITY_UPDATED, OPPORTUNITY_STATUS_CHANGED,
    PROFILE_UPDATED, RESUME_UPLOADED, RESUME_REVIEWED, ADMIN_ACTION
}
