package in.pragati.domain.enums;
public enum Sector {
    SOFTWARE_IT, DATA_ANALYTICS, FINANCE_BANKING, DESIGN_MEDIA, MARKETING_COMMUNICATION,
    PUBLIC_ADMIN_POLICY, HEALTHCARE_BIOTECH, MANUFACTURING_OPERATIONS, RESEARCH_DEVELOPMENT, ENVIRONMENTAL_ENERGY
}
